version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5432:5432"
  stripe-cli:
    image: stripe/stripe-cli
    command: 
      - listen 
      - --forward-to 
      - http://host.docker.internal:8081/api/jobs/webhook
      - --api-key
      - ${STRIPE_API_KEY}
    extra_hosts:
        - "host.docker.internal:host-gateway"